### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Sablam** [BitbanChou/Resident-Evil-8-mod#1]
Hi,

Is this mod made for multiplayer ?

It works on singlepIayer, but I have this issue when trying to start my server with it: 
net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.Joy187.newmod,proxy.CommonProxy
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:102)

As my modpack is quite consequent, it can come from something else.

The full crash-re^prt is in attachment.
[crash-2021-06-15_02.14.34-server.txt](https://github.com/BitbanChou/Resident-Evil-8-mod/files/6652035/crash-2021-06-15_02.14.34-server.txt)

**Comment by BitbanChou** [comment]
> Hi,
> 
> Is this mod made for multiplayer ?
> 
> It works on singlepIayer, but I have this issue when trying to start my server with it:
> net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.Joy187.newmod,proxy.CommonProxy
> at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:102)
> 
> As my modpack is quite consequent, it can come from something else.
> 
> The full crash-re^prt is in attachment.
> [crash-2021-06-15_02.14.34-server.txt](https://github.com/BitbanChou/Resident-Evil-8-mod/files/6652035/crash-2021-06-15_02.14.34-server.txt)

[bug place](https://cdn.acwing.com/media/article/image/2021/06/16/39383_eec41b5fce-bug.png)
Yeah,there is actually a bug in the CommonProxy,I write the ',' instead of '.' . **Thank you bro~**
I will fix it and publish a new version soon.
